version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: unless-stopped      

  web:
    build: .
    ports:
      - "5000:5000"
      - "80:5000"
    restart: unless-stopped     
    depends_on:
      - elasticsearch


volumes:
  elasticsearch-data:
    driver: local

# STAGING VM NOTES
# /etc/sysctl.conf: vm.max_map_count = 262144