version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    restart: unless-stopped

  #nginx

  web:
    container_name: flask_backend
    build: .
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - ./static:./static
      - ./templates:./templates



volumes:
  elasticsearch-data:
    driver: local

# STAGING VM NOTES
# /etc/sysctl.conf: vm.max_map_count = 262144