version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped

  web:
    container_name: flask_backend
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.key:/etc/nginx/server.key
      - ./server.crt:/etc/nginx/server.crt
    restart: unless-stopped
    depends_on:
      - web


volumes:
  elasticsearch-data:
    driver: local

# STAGING VM NOTES
# /etc/sysctl.conf: vm.max_map_count = 262144