version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    restart: unless-stopped

  web:
    container_name: flask_backend
    build: .
    expose: 
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./static:/usr/joyce/static
      - ./setup:/usr/joyce/setup
      - ./blueprints:/usr/joyce/blueprints
      - ./templates:/usr/joyce/templates
      - ./.env:/usr/joyce/.env
      - ./config.py:/usr/joyce/config.py
      - ./application.py:/usr/joyce/application.py
    restart: unless-stopped
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./server.key:/etc/nginx/server.key
      # - ./server.crt:/etc/nginx/server.crt
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
    restart: unless-stopped
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw


volumes:
  elasticsearch-data:
    driver: local

# STAGING VM NOTES
# /etc/sysctl.conf: vm.max_map_count = 262144