[pytest]
testpaths = tests
norecursedirs =
    node_modules
    joyce-env
    backups
    static
    setup/src
    setup/target
    certbot
    .git
    __pycache__
python_files = test_*.py
python_classes = Test*
python_functions = test_*
